### ISSUE TITLE
Migraties aanmaken voor ContentPage en File

### ISSUE THREAD

**Issue by releaznl** [releaznl/yii-contentbeheer#3]
Als we straks de module ingericht hebben moeten ook migraties kunnen worden uitgevoerd om alle tabellen aan te maken. Tabellen die we nu hebben zijn die van ContentPage en File. Maak alvast een migratie aan voor deze beide tabellen.

**Comment by releaznl** [comment]
Als je op http://www.yiiframework.com/doc-2.0/guide-db-migrations.html zoekt naar migrationPath dan zie je dat je ook migraties in een andere locatie kunt uitvoeren. De migraties voor CMS module kun je dan dus ook in de CMS module zetten.

**Comment by HellFly** [comment]
'modules' => [
        'cms' => [
            'class' => 'app\modules\cms\cms',
        ],
    ],
