### ISSUE TITLE
Tonen en selecteren file na uploaden via popup

### ISSUE THREAD

**Issue by releaznl** [releaznl/yii-contentbeheer#5]
Nadat je een file hebt geupload, verschijnt deze niet direct onderaan bij de listed files en kun je hem niet aanklikken om in de tekst te plaatsen. 

Het moet zo zijn dat na het uploaden ook de view eronder (met de thumbs) wordt gerefreshed zodat je direct de file die je hebt geupload in de tekst kunt zetten.

**Comment by HellFly** [comment]
- Initiële volgorde nog niet goed, moet van meest recent geüpdate naar minst recent
